---
## Opt view config

# Set this to false to disable remark_filters list
use_remark_filters: true

# Exclude optimization remarks with names matching this regex:
exclude_names: NeverInline|NotPossible|LoopSpillReloadCopies
# Exclude optimization remarks with text matching this regex:
exclude_text: ^std\:\:|^__dynamic_cast|^operator new|^operator delete|^__cxa|^__clang

# Collect all optimization remarks, not just failures
collect_opt_success: False

# Maximum number of the hottest remarks to appear on the index page
max_hottest_remarks_on_index: 1000

# Annotate all files, including system headers
annotate_external: false
